apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - image: webapp-front
      context: ./client/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NGINX_VER: 1.17.10-alpine
      sync:
        manual:
          - src: 'src/dist/*'
            dest: /usr/share/nginx/html
    - image: webapp-api
      context: ./server/
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GOLANG_VER: 1.14.2
          ALPINE_VER: 3.11
deploy:
  kubectl:
    manifests:
      - ./common/k8s/*
      - ./client/k8s/*
      - ./server/k8s/*
profiles:
- name: local
  build:
    local:
      push: false
  deploy:
    kubeContext: minikube
