apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-api-deployment
  labels:
    app: webapp-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-api
      tier: backend
  template:
    metadata:
      labels:
        app: webapp-api
        tier: backend
    spec:
      containers:
        - name: webapp-api
          image: webapp-api
          ports:
            - containerPort: 8080
