version: '3'

services:

  # Dockerイメージの作成
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        ANGULAR_VERSION: ${ANGULAR_VERSION}
    image: "angular9-app"
    container_name: "angular9-app"
    
  # create application
  app-create:
    image: "angular9-app"
    volumes:
      - "${ANGULAR_APP_PATH}:/app"
    command: bash -c "ng new ${ANGULAR_APP_NAME} --style=scss --directory ./"
    depends_on:
      - base
    
  # init node_modules
  app-init:
    image: "angular9-app"
    volumes:
      - "${ANGULAR_APP_PATH}:/app"
    command: bash -c "npm cache clean --force && npm install"
    depends_on:
      - base

  # api mock
  api-mock:
    image: "stoplight/prism:${PRISM_VER}"
    ports:
      - "4010:4010"
    volumes:
      - "${PRISM_MOUNT_PATH}:/tmp"
    command: "mock -h 0.0.0.0 -d /tmp/${PRISM_API_PATH}"

  # ng serve
  ng-serve:
    image: "angular9-app"
    ports:
      - "4200:4200"
    volumes:
      - "${ANGULAR_APP_PATH}:/app"
    command: bash -c "npm rebuild node-sass && ng serve --host 0.0.0.0"
    depends_on:
      - base

  # ng build
  ng-build:
    image: "angular9-app"
    volumes:
      - "${ANGULAR_APP_PATH}:/app"
    command: bash -c "ng build --prod --output-path dist --deploy-url=./"
    depends_on:
      - base
